# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/lcu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10protos/lcu.proto\x1a\x1egoogle/protobuf/wrappers.proto"F\n\x10LcuClientMessage\x12$\n\x0clcu_announce\x18\x01 \x01(\x0b\x32\x0c.LcuAnnounceH\x00\x42\x0c\n\nlcu_client"A\n\x12LcuResponseMessage\x12\x1b\n\x07success\x18\x01 \x01(\x0b\x32\x08.SuccessH\x00\x42\x0e\n\x0clcu_response"j\n\x0bLcuAnnounce\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue"\t\n\x07Successb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.lcu_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _LCUCLIENTMESSAGE._serialized_start = 52
    _LCUCLIENTMESSAGE._serialized_end = 122
    _LCURESPONSEMESSAGE._serialized_start = 124
    _LCURESPONSEMESSAGE._serialized_end = 189
    _LCUANNOUNCE._serialized_start = 191
    _LCUANNOUNCE._serialized_end = 297
    _SUCCESS._serialized_start = 299
    _SUCCESS._serialized_end = 308
# @@protoc_insertion_point(module_scope)
